name: Dev Deployment

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v3

      # Step 2: Setup Node.js v22
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # match your local version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install


      # Step 4: Build project
      - name: Build
        run: npm run build   # make sure this exists in package.json

      # Step 5: Deploy to Dev server
      - name: Deploy to Dev Server
        run: echo "Deploying to Dev environment..."  # replace with your deploy command
